[package]
name = "bitwise_patterns"
version = "0.1.0"
authors = ["wdhg <wdhgrant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
rand = { version = "0.7.3", features = ["small_rng"] }
